### ISSUE TITLE
Info on the API (Want to get a list of all available films)

### ISSUE THREAD

**Issue by asn-d6** [jdennes/mubi#3]
Hello! Thanks for working on this project!

I did use it yesterday with success, but I didn't achieve my final goal which was to pipe the "now showing" movies of MUBI to IMDb to get their IMDb ratings.

I'd like to submit a PR to allow this project to also display the "now showing" movies of MUBI, but I don't really know how I can get that from their API. 

This brings me to my question: How did you learn about the MUBI API? I don't see any info about it on their website.

I also found out `/services/api/films` which gives you a json list of 25 films on MUBI  starting with `id=1`, but in classic MUBI fashion those films are not even watchable (they are not in the "now showing" or "library")... So I'm not sure how to get the actually available films using the API. Any hints?

Thanks a lot!

**Comment by jdennes** [comment]
Hi @asn-d6,

> How did you learn about the MUBI API? I don't see any info about it on their website.

As far as I know there is no official documented Mubi API. I just discovered the endpoints here by using developer tools, so this project is more fun than something that should be considered very reliable. :)

> I also found out `/services/api/films` which gives you a json list of 25 films on MUBI starting with `id=1`, but in classic MUBI fashion those films are not even watchable (they are not in the "now showing" or "library")... So I'm not sure how to get the actually available films using the API. Any hints?

I got curious about this, but didn't find much. I can only find a JSON object containing the data which needs to be scraped from https://mubi.com/film-of-the-day.

I added a simple function in https://github.com/jdennes/mubi/pull/4.

**Comment by asn-d6** [comment]
Hey @jdennes ! That worked great over here! Even tho it's not all films and it's only film-of-the-day that's something too.

If you manage to find the API endpoint to get the whole library let me know and I can do the PR for you :)

If you are interested in a script that goes through the film-of-the-day and gets you IMDb reviews, let me know ;)

Thanks a lot!!! :)
